name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]
  # Isse tum manually bhi button daba kar sync kar sakte ho
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Latest version
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Git configuration
          git config --global user.email "shantanupathak94@gmail.com"
          git config --global user.name "shantanu"
          
          # Force push to HF Space (shantanupathak94/Ai-code-editor)
          git remote add hf https://shantanupathak94:$HF_TOKEN@huggingface.co/spaces/shantanupathak94/Ai-code-editor
          git push --force hf main
