{
  "files": [
    {
      "path": ".github/workflows/sync_to_hf.yml",
      "content": "name: Sync to Hugging Face Hub\n\non:\n  push:\n    branches: [main]\n  workflow_dispatch:\n\njobs:\n  sync-to-hub:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v3\n        with:\n          fetch-depth: 0\n          lfs: true\n      - name: Push to Hugging Face Hub\n        env:\n          HF_TOKEN: ${{ secrets.HF_TOKEN }}\n          HF_USER: \"shantanupathak94\"\n          HF_SPACE: \"Ai-code-editor\"\n        run: |\n          git config --global user.email \"shantanupathak94@gmail.com\"\n          git config --global user.name \"shantanu\"\n          \n          git remote add hf https://user:$HF_TOKEN@huggingface.co/spaces/$HF_USER/$HF_SPACE\n          git push -f hf main\n"
    }
  ]
}
